dNameConvension = {
	'type': {
		'group': 'grp',
		'null': 'null',
		'rigGroup': 'rig',
		'locator': 'loc',
		'joint': 'jnt',
		'mesh': 'mesh',
		'curve': 'crv',
		'surface': 'surf',
		'control': 'ctrl',
		'stack': 'stack',
		'passer': 'passer',
		'zero': 'zero',
		'skinCluster': 'skin',
		'xtrans': 'xtrs',
		'blendshape': 'bs',
		'cluster': 'cls',
		'lattice': 'lat',
		'wrap': 'wrap',
		'blueprint': 'bpJnt',
		'bindJoint': 'bindJnt',
		'ikHandle': 'ikHnd',
		'follicle': 'fol',
		'plusMinusAverage': 'pmav',
		'multiplyDivide': 'multDv',
		'addDoubleLinear': 'add',
		'multDoubleLinear': 'mult',
		'condition': 'cond',
		'reverse': 'rvs',
		'remapValue': 'remap',
		'curveInfo': 'crvInfo',
		'distanceBetween': 'disBtw',
		'composeMatrix': 'compMatrix',
		'decomposeMatrix': 'decompMatrix',
		'multMatrix': 'multMatrix',
		'addMatrix': 'addMatrix',
		'inverseMatrix': 'inverseMatrix',
		'quatToEuler': 'quatToEuler',
		'blendColors': 'blend',
		'clamp': 'clamp',
		'closetPointOnMesh': 'clsPntOnMesh',
		'closetPointOnSurface': 'clsPntOnSurf',
		'nearestPointOnCurve': 'clsPntOnCrv',
		'pointOnCurveInfo': 'pntOnCrvInfo',
		'pointOnSurfaceInfo': 'pntOnSurfInfo',
		'choice': 'choice',
		'rigComponent': 'rigComponent',
		'xform': 'xform',
		'rigNodesWorld': 'rigsWorld',
		'subComponents': 'subComponents',
		'space': 'space',
		'controlsXform': 'controlsXform',
		'controls': 'controls',
		'joints': 'joints',
		'driveJoints': 'drvJoints',
		'bindJoints': 'bindJoints',
		'rigNodesLocal': 'rigsLocal',
		},

	'side': {
		'left': 'l',
		'right': 'r',
		'middle': 'm',
		'up': 'u',
		'down': 'd',
		'front': 'f',
		'back': 'b',
		'leftFront': 'lf',
		'leftBack': 'lb',
		'leftUp': 'lu',
		'leftDown': 'ld',
		'rightFront': 'rf',
		'rightBack': 'rb',
		'rightUp': 'ru',
		'rightDown': 'rd',
		'middleFront': 'mf',
		'middleBack': 'mb',
		'middleUp': 'mu',
		'middleDown': 'md'
	},

	'resolution':{
		'high': 'high',
		'middle': 'mid',
		'low': 'low',
		'proxy': 'proxy',
		'simulation': 'sim'
	},
}

dNameConvensionInverse = {}
for sKey in dNameConvension.keys():
	dInverse = {sKey: {v: k for k, v in dNameConvension[sKey].iteritems()}}
	dNameConvensionInverse.update(dInverse)

spaceDict = {
				'fk': 0,
				'ik': 1,
				}