import os

dirname = os.path.abspath(os.path.dirname(__file__))

green = os.path.join(dirname, 'green.png')
red = os.path.join(dirname, 'red.png')
yellow = os.path.join(dirname, 'yellow.png')
grey = os.path.join(dirname, 'grey.png')
unCheck = os.path.join(dirname, 'unCheck.png')
reload = os.path.join(dirname, 'reload.png')
reload_disabled = os.path.join(dirname, 'reload_disabled.png')
execute_select = os.path.join(dirname, 'execute_select.png')
execute_select_disabled = os.path.join(dirname, 'execute_select_disabled.png')
pause = os.path.join(dirname, 'pause.png')
pause_disabled = os.path.join(dirname, 'pause_disabled.png')
resume = os.path.join(dirname, 'resume.png')
stop = os.path.join(dirname, 'stop.png')
stop_disabled = os.path.join(dirname, 'stop_disabled.png')
execute_all = os.path.join(dirname, 'execute_all.png')
execute_all_disabled = os.path.join(dirname, 'execute_all_disabled.png')
reload_execute = os.path.join(dirname, 'reload_execute.png')
reload_execute_disabled = os.path.join(dirname, 'reload_execute_disabled.png')
task_new = os.path.join(dirname, 'task_new.png')
task_reference = os.path.join(dirname, 'task_reference.png')
callback_new = os.path.join(dirname, 'callback_new.png')
callback_reference = os.path.join(dirname, 'callback_reference.png')
method = os.path.join(dirname, 'method.png')